spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: 'false'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

#server:
#  port : 13000

database:
  url: ${DATABASE_URL}

  orders-service:
    url: "https://rethink-backend-orders.herokuapp.com/order"
    endpoints:
      order-status: "/status"